spring:
  config:
    import: optional:configserver:http://localhost:1083/user-service/

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    #    username: postgres
    username: user_HEtrkZ
    #    password: password_dev
    password: password_xya85y
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect