spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
    username: gitea_Gk2NEP
#    password: password_dev
    password: gitea_7Em7JB
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql:
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

    locations: classpath:db/migration
    schemas: public
    placeholders:
      schema: public

#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml

server:
  port: 8089
