spring:
  application:
    name: user-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh

custom:
  welcome-message: "Hello from User Service!"