spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
server:
  port: 1083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true